### ISSUE TITLE
Shall it contain a check for debug_assertions like fake-static? 

### ISSUE THREAD

**Issue by vi** [ben0x539/totally-safe-transmute#4]
https://github.com/NieDzejkob/fake-static/blob/master/src/lib.rs#L3

I think inclusion of `#[cfg(not(debug_assertions))] compile_error!("...");` should be a tradition for such proof-of-unsoundness crates, unless they work only in `--release` mode.

**Comment by ben0x539** [comment]
Thanks for the pointer! I wasn't aware of that pattern, but I'd prefer not to add it to this repo, mostly for aesthetic reasons. I don't think there is a real danger this is going to cause trouble in production. (Also, if it did, it could arguably be very funny for bystanders.)

also cripes the lifetimes in fake-static are giving me a headache
